from w4t_waste_collection.models.collection_points import DepositPoint, DepositPointType, DepositPointIsle
from w4t_waste_collection.models.monitoring import KeyPerformanceIndicator
from w4t_waste_collection.models.treatament import TreatmentPlantType, TreatmentPlant
from w4t_waste_collection.models.waste_characterizations import SortingType, ResourceCategory, Resource
from w4t_waste_collection.models.social import Action
