
from w4t_waste_collection.models.collection_points import DepositPoint, DepositPointType, DepositPointIsle
from w4t_waste_collection.models.waste_characterizations import SortingType, Waste, WasteCategory, WasteManagementStage