# Generated by Django 2.0.5 on 2018-05-07 13:53

from django.db import migrations, models
import django.db.models.deletion
import django_orion_model.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_orion_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('orionentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_orion_model.OrionEntity')),
                ('name', django_orion_model.models.OrionCharField(blank=True, max_length=1011, verbose_name='name')),
                ('alt_name', django_orion_model.models.OrionCharField(blank=True, max_length=1024, verbose_name='alternateName')),
                ('organization', django_orion_model.models.OrionCharField(blank=True, max_length=1024, verbose_name='organization')),
                ('process', django_orion_model.models.OrionCharField(blank=True, max_length=1024, verbose_name='process')),
                ('product', django_orion_model.models.OrionCharField(blank=True, max_length=1024, verbose_name='product')),
                ('provider', django_orion_model.models.OrionCharField(blank=True, max_length=1024, verbose_name='provider')),
                ('business_target', django_orion_model.models.OrionCharField(blank=True, max_length=1024, verbose_name='businessTarget')),
                ('description', django_orion_model.models.OrionTextField(blank=True, max_length=1024, verbose_name='description')),
                ('calculation_frequency', django_orion_model.models.OrionCharField(blank=True, max_length=1024, verbose_name='calculationFrequency')),
                ('category', django_orion_model.models.OrionCharField(blank=True, max_length=1024, verbose_name='category')),
                ('calculated_by', django_orion_model.models.OrionCharField(blank=True, max_length=1024, verbose_name='calculatedBy')),
                ('calculation_method', django_orion_model.models.OrionCharField(blank=True, max_length=1024, verbose_name='calculationMethod')),
                ('calculation_formula', django_orion_model.models.OrionCharField(blank=True, max_length=1024, verbose_name='calculationFormula')),
                ('aggregated_data', django_orion_model.models.OrionCharField(blank=True, max_length=1024, verbose_name='aggregatedData')),
                ('calculation_period', django_orion_model.models.OrionCharField(blank=True, max_length=1024, verbose_name='calculationPeriod')),
                ('current_standing', django_orion_model.models.OrionCharField(blank=True, max_length=1024, verbose_name='currentStanding')),
                ('kpi_value', django_orion_model.models.OrionFloatField(blank=True, null=True, verbose_name='kpiValue')),
                ('date_created', django_orion_model.models.OrionDateTimeField(blank=True, null=True, verbose_name='dateCreated')),
                ('expected_value', django_orion_model.models.OrionFloatField(blank=True, null=True, verbose_name='expectedValue')),
                ('date_next_calculation', django_orion_model.models.OrionDateTimeField(blank=True, null=True, verbose_name='dateNextCalculation')),
                ('date_expires', django_orion_model.models.OrionDateTimeField(blank=True, null=True, verbose_name='dateExpires')),
                ('date_modified', django_orion_model.models.OrionDateTimeField(blank=True, null=True, verbose_name='dateModified')),
                ('location', django_orion_model.models.OrionCharField(blank=True, max_length=1024, verbose_name='location')),
                ('address', django_orion_model.models.OrionTextField(blank=True, max_length=1024, verbose_name='address')),
                ('area', django_orion_model.models.OrionCharField(blank=True, max_length=1024, verbose_name='area')),
            ],
            bases=('django_orion_model.orionentity',),
        ),
        migrations.CreateModel(
            name='SortingType',
            fields=[
                ('orionentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_orion_model.OrionEntity')),
                ('name', django_orion_model.models.OrionCharField(blank=True, max_length=1024, verbose_name='name')),
                ('description', django_orion_model.models.OrionTextField(blank=True, max_length=1024, verbose_name='description')),
                ('regulation', django_orion_model.models.OrionCharField(blank=True, max_length=1024, verbose_name='regulation')),
                ('color', django_orion_model.models.OrionCharField(blank=True, max_length=1024, verbose_name='color')),
                ('annotations', django_orion_model.models.OrionTextField(blank=True, max_length=1024, verbose_name='annotations')),
                ('area_served', django_orion_model.models.OrionCharField(blank=True, max_length=1024, verbose_name='areaServed')),
            ],
            bases=('django_orion_model.orionentity',),
        ),
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('orionentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_orion_model.OrionEntity')),
                ('name', django_orion_model.models.OrionCharField(blank=True, max_length=1024, verbose_name='name')),
                ('description', django_orion_model.models.OrionTextField(blank=True, max_length=1024, verbose_name='description')),
                ('waste_code', django_orion_model.models.OrionCharField(blank=True, max_length=1024, verbose_name='wasteCode')),
            ],
            bases=('django_orion_model.orionentity',),
        ),
        migrations.CreateModel(
            name='WasteCategory',
            fields=[
                ('orionentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_orion_model.OrionEntity')),
                ('name', django_orion_model.models.OrionCharField(blank=True, max_length=1024, verbose_name='name')),
                ('description', django_orion_model.models.OrionTextField(blank=True, max_length=1024, verbose_name='description')),
            ],
            bases=('django_orion_model.orionentity',),
        ),
        migrations.CreateModel(
            name='WasteManagementStage',
            fields=[
                ('orionentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_orion_model.OrionEntity')),
                ('name', django_orion_model.models.OrionCharField(blank=True, max_length=1024, verbose_name='name')),
                ('description', django_orion_model.models.OrionTextField(blank=True, max_length=1024, verbose_name='description')),
            ],
            bases=('django_orion_model.orionentity',),
        ),
        migrations.AddField(
            model_name='waste',
            name='ref_waste_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waste_collection_model.WasteCategory'),
        ),
        migrations.AddField(
            model_name='sortingtype',
            name='ref_wastes',
            field=models.ManyToManyField(to='waste_collection_model.Waste'),
        ),
    ]
