# Generated by Django 2.0.5 on 2018-05-11 14:07

from django.db import migrations
import django_orion_model.models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_collection_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='aggregated_data',
            field=django_orion_model.models.OrionCharField(blank=True, max_length=1024, verbose_name='aggregated data'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='alt_name',
            field=django_orion_model.models.OrionCharField(blank=True, max_length=1024, verbose_name='alternate name'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='business_target',
            field=django_orion_model.models.OrionCharField(blank=True, max_length=1024, verbose_name='business target'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='calculated_by',
            field=django_orion_model.models.OrionCharField(blank=True, max_length=1024, verbose_name='calculated by'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='calculation_formula',
            field=django_orion_model.models.OrionCharField(blank=True, max_length=1024, verbose_name='calculation formula'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='calculation_frequency',
            field=django_orion_model.models.OrionCharField(blank=True, max_length=1024, verbose_name='calculation frequency'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='calculation_method',
            field=django_orion_model.models.OrionCharField(blank=True, max_length=1024, verbose_name='calculation method'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='calculation_period',
            field=django_orion_model.models.OrionCharField(blank=True, max_length=1024, verbose_name='calculation period'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='current_standing',
            field=django_orion_model.models.OrionCharField(blank=True, max_length=1024, verbose_name='current standing'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='date_created',
            field=django_orion_model.models.OrionDateTimeField(blank=True, null=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='date_expires',
            field=django_orion_model.models.OrionDateTimeField(blank=True, null=True, verbose_name='date of expiration'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='date_modified',
            field=django_orion_model.models.OrionDateTimeField(blank=True, null=True, verbose_name='date of modification'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='date_next_calculation',
            field=django_orion_model.models.OrionDateTimeField(blank=True, null=True, verbose_name='date of next calculation'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='expected_value',
            field=django_orion_model.models.OrionFloatField(blank=True, null=True, verbose_name='expected value'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='kpi_value',
            field=django_orion_model.models.OrionFloatField(blank=True, null=True, verbose_name='kpi value'),
        ),
    ]
