# Generated by Django 2.0.5 on 2018-05-11 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste_collection_model', '0002_auto_20180511_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi',
            name='orionentity_ptr',
        ),
        migrations.DeleteModel(
            name='KPI',
        ),
    ]
